apiVersion: v1
kind: Pod
metadata:
  namespace: weatherbus
  name: prime
  labels:
    app: weatherbus-prime
spec:
  containers:
  - name: prime
    image: weatherbus/prime
    imagePullPolicy: Never
    env:
    - name: WEATHERBUS-BUS_RIBBON_LISTOFSERVERS
      value: http://bus-service.weatherbus.svc.cluster.local:9090
