apiVersion: v1
kind: Service
metadata:
  namespace: weatherbus
  name: prime-service
spec:
  selector:
    app: weatherbus-prime
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
